### ISSUE TITLE
Awkward label dance with getsantry bot whenever we open an issue for our own team

### ISSUE THREAD

**Issue by brentc** [getsentry/team-ospo#107] opened 2023-02-15 15:56 UTC
Not sure if this it the right place to report this so let me know otherwise!

The MDX team is in the process of moving over to GitHub for tracking MDX epics, tasks, and bugs, and also for our ongoing support of D&D work.

Whenever we open a new issue, we have to go through a little labeling dance with getsantry, as seen on getsentry/sentry#44663:
![image](https://user-images.githubusercontent.com/466158/219080217-0e6bcb0a-a985-44f7-b82b-dca563da9db4.png)

Is there some specific process when opening a ticket we can do to not do this? Or alternatively some way to upgrade the bot to be a little smarter when members of `team-mdx` open tickets with `Team: Mobile Developer Experience` / `discover-n-dashboards` open tickets with `Team: Discover & Dashboards`?

**Comment by chadwhitacre** [comment] 2023-02-15 15:59
> Not sure if this it the right place to report this

This is a great place to report this, thanks! 😁

**Comment by chadwhitacre** [comment] 2023-02-15 16:01
We have [a project spec'd out to improve the automations](https://github.com/getsentry/team-ospo/issues/89), this would fit under that. We decided to focus on other things for Q1, though. :-/

Maybe there's some low-hanging fruit somewhere in here though?

**Comment by brentc** [comment] 2023-02-15 18:44
Ok, we can work around it for now. Confirmation that there wasn't an existing process for avoiding that we just weren't doing is good though.

**Comment by brentc** [comment] 2023-02-15 20:23
Hmm, am I [reading this wrong](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/triage.ts#L96), or is the intended workflow that if the user opening the issue is an internal dev the `Status: Untriaged` shouldn't be being applied at all?

**Comment by chadwhitacre** [comment] 2023-02-16 23:25
So it's a little confusing, but `markUntriaged` runs [when issues are opened](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/index.ts#L10) in [repos _other_ than `sentry` and `sentry-docs`](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/index.ts#L10).

What we're seeing at, e.g., https://github.com/getsentry/sentry/issues/44663#event-8527536718, is that:
- [when we apply](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/index.ts#L16) a `Team: Foo` label in the [`sentry` (or `sentry-docs`)](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L20) repo,
- we [remove all other](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L197-L202) `Team: Foo` and `Status: Foo` labels, and
- [apply a fresh](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L226-L231) `Status: Untriaged` label.

(Looks like there's more mess with Status labels but let's stay focused for a second.)

I think for low-hanging fruit, the rule should maybe be that when someone in EPD routes an issue via a `Team: Foo` label, then we should add `Status: Backlog` instead of `Status: Untriaged`.

Thoughts @hubertdeng123, et al.?

**Comment by hubertdeng123** [comment] 2023-02-16 23:41
The reason why there's a weird dance is because our `issue-status-helper.yml` automation tries to guarantee that there is only one `Status: *` label 😬. Honestly, maybe we should just remove the issue status helper automation entirely since I feel like it's not super useful?

Agh, I think the remedy for this is checking to see if the membership of the user who opened the issue before routing. If the issue is made by an internal dev that doesn't belong to the GTM team, then we can skip routing altogether. I did have a PR up that could use a revisit that I planned on tackling after enabling routing for GTM members. I don't think we should default to putting things on the backlog if routed by EPD. If an issue needs to be rerouted, it'll end up on the backlog if a team member reroutes it which really isn't what we want.

**Comment by chadwhitacre** [comment] 2023-02-16 23:44
>> (Looks like there's more mess with Status labels but let's stay focused for a second.)
> The reason why there's a weird dance is because our issue-status-helper.yml automation tries to guarantee that there is only one Status: * label 😬.

Ah, yeah, I think that's for [this](https://github.com/getsentry/sentry/issues/44663#event-8527539385):

<img width="566" alt="action" src="https://user-images.githubusercontent.com/134455/219513050-bef1bb3c-b2ec-4bce-b7f3-e9d8dafc05dd.png">

But we also have [this](https://github.com/getsentry/sentry/issues/44663#event-8527536718):

<img width="941" alt="app" src="https://user-images.githubusercontent.com/134455/219513068-983a5f7f-e1fb-42f1-bef6-622cdfca8c0b.png">

Right?

**Comment by chadwhitacre** [comment] 2023-02-16 23:51
> Honestly, maybe we should just remove the issue status helper automation entirely since I feel like it's not super useful?

I'd be fine with that for a quick fix. Seems really susceptible to race conditions since it runs in an action, which takes 60+ seconds.

> If the issue is made by an internal dev that doesn't belong to the GTM team, then we can skip routing altogether.

Pretty sure [we're already good](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L88) here. On the [example](https://github.com/getsentry/sentry/issues/44663) we don't see **[@getsantry](https://github.com/apps/getsantry)** apply `Status: Unrouted`, right? Hopefully this is because @edwardgou-sentry passes [the test](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L46-L49). 😅

**Comment by hubertdeng123** [comment] 2023-02-16 23:51
That's correct. 

For [this](https://github.com/getsentry/sentry/issues/44663#event-8527536718), we don't want the routing to even happen in the first place

<img width="941" alt="219513068-983a5f7f-e1fb-42f1-bef6-622cdfca8c0b" src="https://user-images.githubusercontent.com/25517925/219513825-f5b2c714-1b69-46ec-821f-0fd8881dfb09.png">


> I think the remedy for this is checking to see if the membership of the user who opened the issue before routing. If the issue is made by an internal dev that doesn't belong to the GTM team, then we can skip routing altogether. I did have a PR up that could use a revisit that I planned on tackling after enabling routing for GTM members. I don't think we should default to putting things on the backlog if routed by EPD.

What I'm saying here addresses this, since we're checking the membership of the user who opened the issue. If it's someone in EPD I'm assuming it's very likely that it's an issue for their own team or they know who to assign it to already.

**Comment by hubertdeng123** [comment] 2023-02-16 23:55
Actually I thought about that again, maybe the best solution is checking the membership of the user who opened the issue.

Internal User (EPD):
1. Skip the routing message
2. Add the `Status: Backlog` label

Internal Member (GTM):
1. Add the `Status: Unrouted` label
2. Route as normal

External Member:
1. Add the `Status: Unrouted` label
2. Route as normal

**Comment by chadwhitacre** [comment] 2023-02-17 00:00
> maybe the best solution is checking the membership of the user who opened the issue.

Pretty sure this is where I landed in https://github.com/getsentry/team-ospo/issues/107#issuecomment-1433876519, yes? 😅

> I think for low-hanging fruit, the rule should maybe be that when someone in EPD (vs. GTM) routes an issue via a `Team: Foo` label, then we should add `Status: Backlog` instead of `Status: Untriaged`.

Assuming we're on the same page (pretty sure we are) then our action items are:

1. Whack [`issue-status-helper.yml`](https://github.com/getsentry/.github/blob/main/.github/workflows/issue-status-helper.yml) (part of #84, really)
2. Modify [`markRouted`](https://github.com/getsentry/eng-pipes/blob/74f67f5eb79cb2245cd57103d8572e0b109e8fc9/src/brain/issueLabelHandler/route.ts#L170) to put on the backlog when routed by EPD.

Look right?

For (2) let's make a note in a code comment that if possible on the other side of #90 we should base backlog/untriaged on membership in the actual affected team (only put on Foo's backlog if routed by members of `Team: Foo` vs. EPD generally).

**Comment by hubertdeng123** [comment] 2023-02-17 00:09
> Pretty sure this is where I landed in https://github.com/getsentry/team-ospo/issues/107#issuecomment-1433876519, yes? 😅

Almost....just the difference between the membership of the user who routed the issue vs the user who opened the issue 😜. If it's done by membership of the user routing we can have the situation where
1. Issue comes in with `Status: Unrouted` label
2. Support routes the issue to `Team: Foo` and automation adds `Status: Untriaged` label
3. `Team: Foo` wants to reroute the issue. A member of the team reroutes to `Team: Bar`. 
4. Issue is rerouted to `Team: Bar` but the `Status: Backlog` label is applied. 


Otherwise we're on the same page here.

**Comment by hubertdeng123** [comment] 2023-02-17 00:14
> only put on Foo's backlog if routed by members of `Team: Foo` vs. EPD generally

Should we rely on the Github membership of teams for this? Last time I checked there seemed to be quite a lot of overlap of people on different teams 😅

**Comment by chadwhitacre** [comment] 2023-02-17 19:07
> Should we rely on the Github membership of teams for this? Last time I checked there seemed to be quite a lot of overlap of people on different teams 😅

Not yet, relying on GitHub teams is theoretical until we get through #90.

> we can have the situation where

Oof, yeah, good call. :-/

**Comment by hubertdeng123** [comment] 2023-02-27 20:20
Removing `issue-status-helper.yml` from all repos. Linking here as a reference to them:
sentry: https://github.com/getsentry/sentry/pull/45127
sentry-docs: https://github.com/getsentry/sentry-docs/pull/6372
.github: https://github.com/getsentry/.github/pull/109
self-hosted: https://github.com/getsentry/self-hosted/pull/1989

**Comment by chadwhitacre** [comment] 2023-12-15 19:52
Closing as not an issue anymore, we are smarter with this now.

**Closed by chadwhitacre** 2023-12-15 19:52 UTC
